name: 'facebook_ads'
version: '0.8.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  facebook_ads:
    +schema: facebook_ads
    +materialized: table
    intermediate:
      +materialized: view
vars:
  facebook_ads:
    account_history: "{{ ref('stg_facebook_ads__account_history') }}"
    ad_history: "{{ ref('stg_facebook_ads__ad_history') }}"
    ad_set_history: "{{ ref('stg_facebook_ads__ad_set_history') }}"
    basic_ad: "{{ ref('stg_facebook_ads__basic_ad') }}"
    basic_ad_actions: "{{ ref('stg_facebook_ads__basic_ad_actions') }}"
    campaign_history: "{{ ref('stg_facebook_ads__campaign_history') }}"
    creative_history: "{{ ref('stg_facebook_ads__creative_history') }}"
    url_tag: "{{ ref('stg_facebook_ads__url_tag') }}"

    facebook_ads__conversion_action_types: # default values
      - name: onsite_conversion.purchase
      - name: onsite_conversion.lead_grouped
      - pattern: offsite_conversion.custom%
      - name: offsite_conversion.fb_pixel_add_payment_info
      - name: offsite_conversion.fb_pixel_add_to_cart
      - name: offsite_conversion.fb_pixel_add_to_wishlist
      - name: offsite_conversion.fb_pixel_complete_registration
      - name: offsite_conversion.fb_pixel_custom
      - name: offsite_conversion.fb_pixel_initiate_checkout
      - name: offsite_conversion.fb_pixel_lead
      - name: offsite_conversion.fb_pixel_purchase
      - name: offsite_conversion.fb_pixel_search
      - name: offsite_conversion.fb_pixel_view_content