name: 'facebook_ads'
version: '0.8.1'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  facebook_ads:
    +schema: facebook_ads
    +materialized: table
    intermediate:
      +materialized: view
vars:
  facebook_ads:
    account_history: "{{ ref('stg_facebook_ads__account_history') }}"
    ad_history: "{{ ref('stg_facebook_ads__ad_history') }}"
    ad_set_history: "{{ ref('stg_facebook_ads__ad_set_history') }}"
    basic_ad: "{{ ref('stg_facebook_ads__basic_ad') }}"
    basic_ad_actions: "{{ ref('stg_facebook_ads__basic_ad_actions') }}"
    basic_ad_action_values: "{{ ref('stg_facebook_ads__basic_ad_action_values') }}"
    campaign_history: "{{ ref('stg_facebook_ads__campaign_history') }}"
    creative_history: "{{ ref('stg_facebook_ads__creative_history') }}"
    url_tag: "{{ ref('stg_facebook_ads__url_tag') }}"
    demographics_country: "{{ ref('stg_facebook_ads__demographics_country') }}"
    demographics_country_actions: "{{ ref('stg_facebook_ads__demographics_country_actions') }}"
    demographics_region: "{{ ref('stg_facebook_ads__demographics_region') }}"
    demographics_region_actions: "{{ ref('stg_facebook_ads__demographics_region_actions') }}"

    facebook_ads__conversion_action_types: # default values
      - name: onsite_conversion.purchase
      - name: onsite_conversion.lead_grouped
      - name: offsite_conversion.fb_pixel_purchase
      - name: offsite_conversion.fb_pixel_lead
      - name: offsite_conversion.fb_pixel_custom # same as pattern: offsite_conversion.custom%