name: 'facebook_ads_integration_tests'
version: '0.8.0'
profile: 'integration_tests'
config-version: 2

vars:
  facebook_ads_schema: facebook_ads_integration_tests
  facebook_ads_account_history_identifier: "facebook_ads_account_history_data"
  facebook_ads_ad_history_identifier: "facebook_ads_ad_history_data"
  facebook_ads_ad_set_history_identifier: "facebook_ads_ad_set_history_data"
  facebook_ads_basic_ad_identifier: "facebook_ads_basic_ad_data"
  facebook_ads_basic_ad_actions_identifier: "facebook_ads_basic_ad_actions_data"
  facebook_ads_basic_ad_action_values_identifier: "facebook_ads_basic_ad_action_values_data"
  facebook_ads_campaign_history_identifier: "facebook_ads_campaign_history_data"
  facebook_ads_creative_history_identifier: "facebook_ads_creative_history_data"
  
  facebook_ads__basic_ad_passthrough_metrics:
    - name: "reach"
    - name: "frequency"
      alias: "fake_freq_name"
  facebook_ads__basic_ad_actions_passthrough_metrics: 
    - name: 'inline'
      alias: 'conversion_value_inline'
    - name: '_1_d_view'
    - name: '_28_d_click'
  facebook_ads__basic_ad_action_values_passthrough_metrics: 
    - name: '_7_d_click'
  facebook_ads__conversion_action_types:
    - name: lead
    - pattern: offsite_conversion%
    - name: onsite_conversion.purchase
      where_sql: 'ad_id != 1234'

models:
  +schema: "facebook_ads_{{ var('directed_schema','dev') }}"

seeds:
  facebook_ads_integration_tests:
    +column_types:
      id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      account_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      campaign_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      ad_set_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      ad_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      creative_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      page_link: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
      template_page_link: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
      _fivetran_synced: "timestamp"
      updated_time: "timestamp"
    facebook_ads_basic_ad_actions_data:
      +column_types:
        value: "float"
        inline: "float"
        _1_d_view: "float"
        _7_d_click: "float"
        
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
