name: '2nd reviewer'
on:
  pull_request_review:
    types: [submitted]

jobs:
  auto_assign_reviewer:
    if: github.event.review.state == 'approved'
    uses: fivetran/dbt_package_automations/.github/workflows/add-2nd-reviewer.yml@main
    secrets: inherit